-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://github.com/pgadmin-org/pgadmin4/issues/new/choose if you find any bugs, including reproduction steps.



CREATE TABLE IF NOT EXISTS prompt_sales."User"
(
    id integer NOT NULL,
    "userNationalId" integer NOT NULL,
    "userFirstName" character varying(30) NOT NULL,
    "userLastName" character varying(30) NOT NULL,
    "userPassword" character varying(50) NOT NULL,
    enabled boolean NOT NULL DEFAULT true,
    "createdAt" timestamp without time zone NOT NULL,
    "updatedAt" timestamp without time zone,
    "lastLogin" timestamp without time zone,
    PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS prompt_sales."UserPermissions"
(
    "permissionId" integer NOT NULL,
    "userId" integer NOT NULL,
    "permisionStatus" boolean NOT NULL DEFAULT true,
    "createdAt" timestamp without time zone NOT NULL,
    "updatedAt" timestamp without time zone,
    enabled boolean NOT NULL DEFAULT true,
    "userEmail" character varying(60),
    PRIMARY KEY ("permissionId", "userId")
);

CREATE TABLE IF NOT EXISTS prompt_sales."Permissions"
(
    "permissionId" integer NOT NULL,
    "permissionCode" character varying(16) NOT NULL,
    "permissionStatus" boolean NOT NULL DEFAULT true,
    "createdAt" timestamp without time zone NOT NULL,
    "updatedAt" timestamp without time zone,
    enabled boolean NOT NULL DEFAULT true,
    module integer NOT NULL,
    PRIMARY KEY ("permissionId")
);

CREATE TABLE IF NOT EXISTS prompt_sales."Modules"
(
    "moduleId" integer NOT NULL,
    "moduleName" character varying(40) NOT NULL,
    PRIMARY KEY ("moduleId")
);

CREATE TABLE IF NOT EXISTS prompt_sales."Applications"
(
    "AppId" integer NOT NULL,
    "appName" character varying(40) NOT NULL,
    "appType" character varying(20) NOT NULL,
    "moduleId" integer,
    PRIMARY KEY ("AppId")
);

CREATE TABLE IF NOT EXISTS prompt_sales."Companies"
(
    "companyId" integer NOT NULL,
    legalld integer NOT NULL,
    "companyName" character varying(40) NOT NULL,
    "legalName" character varying(40) NOT NULL,
    status character varying(30)  NOT NULL,
    "createdAt" date NOT NULL,
    "updatedAt" date,
    enabled boolean DEFAULT true,
    PRIMARY KEY ("companyId")
);

CREATE TABLE IF NOT EXISTS prompt_sales."UserInCompany"
(
    "userId" integer NOT NULL,
    "companyId" integer NOT NULL,
    status character varying(30) NOT NULL,
    "createdAt" date NOT NULL,
    "updatedAt" date,
    enabled boolean NOT NULL DEFAULT true,
    PRIMARY KEY ("userId", "companyId")
);

CREATE TABLE IF NOT EXISTS prompt_sales."PermissionsPerRole"
(
    "roleId" integer NOT NULL,
    "permisionId" integer NOT NULL,
    "createdAt" date NOT NULL,
    "updatedAt" date,
    enabled boolean NOT NULL,
    status character varying(30) NOT NULL,
    PRIMARY KEY ("roleId", "permisionId")
);

CREATE TABLE IF NOT EXISTS prompt_sales."Roles"
(
    "roleId" integer NOT NULL,
    "roleName" character varying(30) NOT NULL,
    "roleStatus" character varying(30) NOT NULL,
    "createdAt" timestamp without time zone NOT NULL,
    "updatedAt" timestamp without time zone,
    PRIMARY KEY ("roleId")
);

CREATE TABLE IF NOT EXISTS prompt_sales."RolesPerUser"
(
    "userId" integer NOT NULL,
    "roleId" integer NOT NULL,
    status character varying(30) NOT NULL,
    "createdAt" timestamp without time zone NOT NULL,
    "upatedAt" timestamp without time zone NOT NULL,
    enabled boolean NOT NULL,
    PRIMARY KEY ("userId", "roleId")
);

CREATE TABLE IF NOT EXISTS prompt_sales."SystemLogs"
(
    "systemLogId" integer NOT NULL,
    description character varying(250),
    "postTime" timestamp without time zone NOT NULL,
    checksum character varying(64),
    "systemLogTypeId" integer NOT NULL,
    "moduleId" integer NOT NULL,
    "userId" integer NOT NULL,
    "logSourceId" integer NOT NULL,
    "logLevelId" integer NOT NULL,
    PRIMARY KEY ("systemLogId")
);

CREATE TABLE IF NOT EXISTS prompt_sales."LogLevels"
(
    "logLevelId" integer NOT NULL,
    name character varying(30) NOT NULL,
    PRIMARY KEY ("logLevelId")
);

CREATE TABLE IF NOT EXISTS prompt_sales."logSources"
(
    "logSourceId" integer NOT NULL,
    name character varying(30) NOT NULL,
    PRIMARY KEY ("logSourceId")
);

CREATE TABLE IF NOT EXISTS prompt_sales."SystemLogTypes"
(
    "systemLogTypeId" integer NOT NULL,
    name character varying(30) NOT NULL,
    PRIMARY KEY ("systemLogTypeId")
);

CREATE TABLE IF NOT EXISTS prompt_sales."Subscription"
(
    "subId" integer NOT NULL,
    "subName" character varying(45) NOT NULL,
    "billingId" integer NOT NULL,
    status character varying(30) NOT NULL,
    description character varying(200),
    "createdAt" timestamp without time zone NOT NULL,
    "updatedAt" timestamp without time zone,
    enabled boolean NOT NULL DEFAULT true,
    PRIMARY KEY ("subId"),
    UNIQUE ("billingId")
);

CREATE TABLE IF NOT EXISTS prompt_sales."Features"
(
    "featureId" integer NOT NULL,
    "featureTypeId" integer NOT NULL,
    name character varying(30) NOT NULL,
    description text NOT NULL,
    enabled boolean NOT NULL DEFAULT false,
    "createdAt" timestamp without time zone NOT NULL,
    "updatedAt" timestamp without time zone NOT NULL,
    PRIMARY KEY ("featureId")
);

CREATE TABLE IF NOT EXISTS prompt_sales."featuresPerSub"
(
    "subId" integer NOT NULL,
    "featureId" integer NOT NULL,
    uses integer NOT NULL,
    enabled boolean NOT NULL DEFAULT true,
    "createdAt" timestamp without time zone NOT NULL,
    "updatedAt" timestamp without time zone,
    PRIMARY KEY ("subId", "featureId")
);

CREATE TABLE IF NOT EXISTS prompt_sales."subsPerUser"
(
    "subId" integer NOT NULL,
    "userId" integer NOT NULL,
    enabled boolean NOT NULL DEFAULT true,
    "createdAt" timestamp without time zone NOT NULL,
    "updatedAt" timestamp without time zone,
    PRIMARY KEY ("subId", "userId")
);

CREATE TABLE IF NOT EXISTS prompt_sales."featureType"
(
    "featureTypeId" integer NOT NULL,
    name character varying(30) NOT NULL,
    description character varying(200),
    PRIMARY KEY ("featureTypeId")
);

CREATE TABLE IF NOT EXISTS prompt_sales."Payments"
(
    "paymentId" integer NOT NULL,
    amount numeric(12, 2) NOT NULL,
    "createdAt" timestamp without time zone NOT NULL,
    "updatedAt" timestamp without time zone,
    status character varying(30) NOT NULL,
    cheksum character varying(64),
    "paymentTypeId" integer NOT NULL,
    "companyId" integer NOT NULL,
    "subId" integer NOT NULL,
    "currencyId" integer NOT NULL,
    "paymentMethodId" integer NOT NULL,
    PRIMARY KEY ("paymentId")
);

CREATE TABLE IF NOT EXISTS prompt_sales."PaymentTypes"
(
    "paymentTypeId" integer NOT NULL,
    name character varying(30),
    PRIMARY KEY ("paymentTypeId")
);

CREATE TABLE IF NOT EXISTS prompt_sales."paymentMethod"
(
    "paymentMetId" integer NOT NULL,
    name character varying(30),
    PRIMARY KEY ("paymentMetId")
);

CREATE TABLE IF NOT EXISTS prompt_sales."Currency"
(
    "currencyId" integer NOT NULL,
    name character varying(30) NOT NULL,
    code bit varying(4) NOT NULL,
    symbol character varying(2) NOT NULL,
    "countryId" integer NOT NULL,
    PRIMARY KEY ("currencyId")
);

CREATE TABLE IF NOT EXISTS prompt_sales."ExchangeRate"
(
    "exchangeRateId" integer NOT NULL,
    "startDate" timestamp without time zone NOT NULL,
    "endDate" timestamp without time zone,
    "fromCurrency" integer NOT NULL,
    "toCurrency" integer NOT NULL,
    enabled boolean NOT NULL DEFAULT true,
    PRIMARY KEY ("exchangeRateId"),
    UNIQUE ("fromCurrency"),
    UNIQUE ("toCurrency")
);

CREATE TABLE IF NOT EXISTS prompt_sales."Country"
(
    "countryId" integer NOT NULL,
    name character varying(30),
    PRIMARY KEY ("countryId")
);

COMMENT ON TABLE prompt_sales."Country"
    IS 'Se ocupa todo el patron de direcciones?
o solo como se ocupa el país está bien';

CREATE TABLE IF NOT EXISTS prompt_sales."Campaigns"
(
    "campaignId" integer NOT NULL,
    "companyId" integer NOT NULL,
    name character varying,
    status character varying(30) NOT NULL,
    "startDate" timestamp without time zone NOT NULL,
    "endDate" timestamp without time zone,
    enabled boolean NOT NULL DEFAULT true,
    "budgetAmount" numeric(10, 2) NOT NULL,
    "createdAt" timestamp without time zone NOT NULL,
    "updatedAt" timestamp without time zone,
    description character varying(200),
    "intereractionsId" integer NOT NULL,
    "calculatiosId" integer NOT NULL,
    PRIMARY KEY ("campaignId")
);

CREATE TABLE IF NOT EXISTS prompt_sales."ContactMethods"
(
    "contactMethodId" integer NOT NULL,
    value character varying(100) NOT NULL,
    status character varying(30) NOT NULL,
    "createdAt" timestamp without time zone NOT NULL,
    "updatedAt" timestamp without time zone,
    enabled boolean NOT NULL DEFAULT true,
    "contactTypeId" integer NOT NULL,
    PRIMARY KEY ("contactMethodId"),
    UNIQUE ("contactTypeId")
);

CREATE TABLE IF NOT EXISTS prompt_sales."ContactMethodTypes"
(
    "TypeId" integer NOT NULL,
    name character varying(30) NOT NULL,
    PRIMARY KEY ("TypeId")
);

CREATE TABLE IF NOT EXISTS prompt_sales."contactCompany"
(
    "companyId" integer NOT NULL,
    "contactMehodId" integer NOT NULL,
    status character varying(40) NOT NULL,
    "createdAt" timestamp without time zone NOT NULL,
    "updatedAt" timestamp without time zone,
    enabled boolean NOT NULL DEFAULT true,
    PRIMARY KEY ("companyId", "contactMehodId")
);

CREATE TABLE IF NOT EXISTS prompt_sales."UserContact"
(
    "UserId" integer NOT NULL,
    "contactMehodId" integer NOT NULL,
    status character varying(40) NOT NULL,
    "createdAt" timestamp without time zone NOT NULL,
    "updatedAt" timestamp without time zone,
    enabled boolean NOT NULL DEFAULT true,
    PRIMARY KEY ("contactMehodId", "UserId")
);

CREATE TABLE IF NOT EXISTS prompt_sales."Interactions"
(
    "interactionId" integer NOT NULL,
    clicks integer,
    likes integer,
    comments integer,
    reactions integer,
    shares integer,
    "usersReached" integer,
    PRIMARY KEY ("interactionId")
);

CREATE TABLE IF NOT EXISTS prompt_sales."Calculations"
(
    "calculoId" integer NOT NULL,
    "clickRate" numeric(6, 3),
    "conversionRate" numeric(6, 3),
    "ROI" numeric(9, 3),
    "engagementRate" numeric(6, 3),
    "createdAt" timestamp without time zone,
    "totalSpent" numeric(10, 2),
    "totalRevenue" numeric(10, 2),
    PRIMARY KEY ("calculoId")
);

CREATE TABLE IF NOT EXISTS prompt_sales."CampaignChannels"
(
    "channelId" integer NOT NULL,
    "campaignId" integer NOT NULL,
    name character varying(30) NOT NULL,
    "totalSpent" numeric(10, 2),
    "createdAt" timestamp without time zone NOT NULL,
    "updatedAt" timestamp without time zone,
    enabled boolean NOT NULL DEFAULT true,
    PRIMARY KEY ("channelId")
);

CREATE TABLE IF NOT EXISTS prompt_sales."Leads"
(
    "leadId" integer NOT NULL,
    "campaignId" integer NOT NULL,
    "sourceSystem" integer,
    name character varying(60) NOT NULL,
    email character varying(60) NOT NULL,
    "number" character varying(20) NOT NULL,
    "countryId" integer NOT NULL,
    status character varying(30) NOT NULL,
    score numeric(3, 1),
    "createdAt" timestamp without time zone NOT NULL,
    "updatedAt" timestamp without time zone,
    enabled boolean NOT NULL DEFAULT true,
    PRIMARY KEY ("leadId"),
    UNIQUE ("countryId")
);

CREATE TABLE IF NOT EXISTS prompt_sales."salesSummary"
(
    "salesSumId" integer NOT NULL,
    "campaignId" integer NOT NULL,
    "countryId" integer NOT NULL,
    date date NOT NULL,
    orders integer NOT NULL,
    "salesAmount" numeric(10, 2) NOT NULL,
    "returnsAmount" numeric(10, 2) NOT NULL,
    "adsRevenue" numeric(10, 2) NOT NULL,
    "sourceSystemId" character varying(30),
    currencyd integer,
    PRIMARY KEY ("salesSumId")
);

CREATE TABLE IF NOT EXISTS prompt_sales."CampaignMarkets"
(
    "marketId" integer NOT NULL,
    "AddressId" integer NOT NULL,
    "budgetAllocation" numeric(5, 2) NOT NULL,
    enabled boolean NOT NULL DEFAULT true,
    "createdAt" timestamp without time zone NOT NULL,
    "updatedAt" timestamp without time zone,
    "campaignId" integer NOT NULL,
    PRIMARY KEY ("marketId")
);

CREATE TABLE IF NOT EXISTS prompt_sales."Addresses"
(
    "AddressId" integer NOT NULL,
    address1 character varying(60) NOT NULL,
    address2 character varying(60) NOT NULL,
    zipcode character varying(12) NOT NULL,
    geolocation point NOT NULL,
    status character varying(30) NOT NULL,
    "createdAt" timestamp without time zone NOT NULL,
    "updatedAt" timestamp without time zone,
    enabled boolean NOT NULL DEFAULT true,
    "cityId" integer NOT NULL,
    PRIMARY KEY ("AddressId")
);

CREATE TABLE IF NOT EXISTS prompt_sales."Cities"
(
    "cityId" integer NOT NULL,
    name character varying(40) NOT NULL,
    "stateId" integer NOT NULL,
    PRIMARY KEY ("cityId")
);

CREATE TABLE IF NOT EXISTS prompt_sales."States"
(
    "StateId" integer NOT NULL,
    name character varying(40) NOT NULL,
    "countryId" integer NOT NULL,
    PRIMARY KEY ("StateId")
);

CREATE TABLE IF NOT EXISTS prompt_sales."Providers"
(
    "providerId" integer NOT NULL,
    "providerTypeId" integer NOT NULL,
    name character varying(40) NOT NULL,
    "baseUrl" character varying(200) NOT NULL,
    status character varying(40),
    description character varying(250),
    "createdAt" timestamp without time zone NOT NULL,
    "updatedAt" timestamp without time zone,
    enabled boolean NOT NULL DEFAULT true,
    PRIMARY KEY ("providerId")
);

CREATE TABLE IF NOT EXISTS prompt_sales."ProviderTypes"
(
    "provderTypeId" integer NOT NULL,
    name character varying(40) NOT NULL,
    description character varying(250),
    "createdAt" timestamp without time zone NOT NULL,
    "updatedAt" timestamp without time zone,
    enabled boolean NOT NULL DEFAULT true,
    PRIMARY KEY ("provderTypeId")
);

CREATE TABLE IF NOT EXISTS prompt_sales."ProviderAPIs"
(
    "apiId" integer NOT NULL,
    "providerId" integer NOT NULL,
    name character varying(40) NOT NULL,
    "baseUrl" character varying(200) NOT NULL,
    "authId" integer NOT NULL,
    enabled boolean NOT NULL DEFAULT true,
    "createdAt" timestamp without time zone NOT NULL,
    "updatedAt" timestamp without time zone,
    request jsonb NOT NULL,
    response jsonb,
    endpoint character varying(100) NOT NULL,
    "typeId" integer,
    PRIMARY KEY ("apiId")
);

CREATE TABLE IF NOT EXISTS prompt_sales."MCPServers"
(
    "mcpId" integer NOT NULL,
    "providerId" integer NOT NULL,
    name character varying(40) NOT NULL,
    url character varying(200) NOT NULL,
    "maxConcurrentCalls" integer NOT NULL,
    "authId" integer NOT NULL,
    enabled boolean NOT NULL DEFAULT true,
    "lastCall" timestamp without time zone,
    "createdAt" timestamp without time zone,
    "updatedAt" integer NOT NULL,
    PRIMARY KEY ("mcpId")
);

CREATE TABLE IF NOT EXISTS prompt_sales."AuthMethods"
(
    "authId" integer NOT NULL,
    name character varying(30) NOT NULL,
    description character varying(200),
    enabled boolean NOT NULL DEFAULT true,
    "createdAt" timestamp without time zone NOT NULL,
    "updatedAt" timestamp without time zone,
    PRIMARY KEY ("authId")
);

CREATE TABLE IF NOT EXISTS prompt_sales."IntegrationCalls"
(
    "callId" integer NOT NULL,
    "companyId" integer NOT NULL,
    "providerId" integer NOT NULL,
    "apiId" integer,
    "mcpToolId" integer,
    operation character varying NOT NULL,
    "responseTime" interval NOT NULL,
    "excecutedAt" timestamp without time zone NOT NULL,
    status character varying NOT NULL,
    "updatedAt" timestamp without time zone,
    PRIMARY KEY ("callId")
);

CREATE TABLE IF NOT EXISTS prompt_sales."callErrors"
(
    "errorId" integer NOT NULL,
    "callId" integer NOT NULL,
    "errorCode" character varying(20) NOT NULL,
    "errorMessage" character varying(150) NOT NULL,
    "errorTypeId" integer,
    retryable boolean NOT NULL DEFAULT true,
    "createdAt" timestamp without time zone NOT NULL,
    PRIMARY KEY ("errorId")
);

CREATE TABLE IF NOT EXISTS prompt_sales."CallErrorTypes"
(
    "typeId" integer NOT NULL,
    name character varying(50) NOT NULL,
    PRIMARY KEY ("typeId")
);

CREATE TABLE IF NOT EXISTS prompt_sales."CallRetryLog"
(
    "retryId" integer NOT NULL,
    "callId" integer NOT NULL,
    attempts integer NOT NULL,
    "maxAttempts" integer NOT NULL,
    "createdAt" timestamp without time zone NOT NULL,
    "updadtedAt" timestamp without time zone,
    status character varying,
    PRIMARY KEY ("retryId")
);

CREATE TABLE IF NOT EXISTS prompt_sales."ETLJobs"
(
    "jobId" integer NOT NULL,
    name character varying(30) NOT NULL,
    description character varying(200) NOT NULL,
    "sourceSystem" character varying(30) NOT NULL,
    enabled boolean NOT NULL DEFAULT true,
    "createdAt" timestamp without time zone NOT NULL,
    "updatedAt" timestamp without time zone,
    "endpointId" integer,
    "targetTable" character varying,
    PRIMARY KEY ("jobId")
);

CREATE TABLE IF NOT EXISTS prompt_sales."ApiTypes"
(
    "typeId" integer NOT NULL,
    name character varying(50) NOT NULL,
    PRIMARY KEY ("typeId")
);

CREATE TABLE IF NOT EXISTS prompt_sales."ETLDeltas"
(
    "deltaId" integer NOT NULL,
    "jobId" integer NOT NULL,
    "sourceSystem" character varying(30) NOT NULL,
    "deltaTypeId" integer NOT NULL,
    description character varying(200) NOT NULL,
    "createdAt" timestamp without time zone NOT NULL,
    "updatedAt" timestamp without time zone,
    status character varying(30) NOT NULL,
    "entityName" character varying(30),
    PRIMARY KEY ("deltaId"),
    UNIQUE ("deltaTypeId")
);

CREATE TABLE IF NOT EXISTS prompt_sales."DeltaTypes"
(
    "TypeId" integer NOT NULL,
    name character varying(30) NOT NULL,
    PRIMARY KEY ("TypeId")
);

CREATE TABLE IF NOT EXISTS prompt_sales."SubBilling"
(
    "billingId" integer NOT NULL,
    "paymentFrequency" character varying(30) NOT NULL,
    "startDate" timestamp without time zone NOT NULL,
    "endDate" timestamp without time zone NOT NULL,
    status character varying(30) NOT NULL,
    price numeric(6, 2) NOT NULL,
    PRIMARY KEY ("billingId")
);


ALTER TABLE IF EXISTS prompt_sales."Permissions"
    ADD FOREIGN KEY (module)
    REFERENCES prompt_sales."Modules" ("moduleId") MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS prompt_sales."UserPermissions"
    ADD FOREIGN KEY ("userId")
    REFERENCES prompt_sales."User" (id)
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;

ALTER TABLE IF EXISTS prompt_sales."UserPermissions"
    ADD FOREIGN KEY ("permissionId")
    REFERENCES prompt_sales."Permissions" ("permissionId")
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS prompt_sales."Applications"
    ADD FOREIGN KEY ("moduleId")
    REFERENCES prompt_sales."Modules" ("moduleId") MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS prompt_sales."UserInCompany"
    ADD FOREIGN KEY ("companyId")
    REFERENCES prompt_sales."Companies" ("companyId") MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS prompt_sales."UserInCompany"
    ADD FOREIGN KEY ("userId")
    REFERENCES prompt_sales."User" (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS prompt_sales."PermissionsPerRole"
    ADD FOREIGN KEY ("permisionId")
    REFERENCES prompt_sales."Permissions" ("permissionId") MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS prompt_sales."PermissionsPerRole"
    ADD FOREIGN KEY ("roleId")
    REFERENCES prompt_sales."Roles" ("roleId") MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS prompt_sales."RolesPerUser"
    ADD FOREIGN KEY ("userId")
    REFERENCES prompt_sales."User" (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS prompt_sales."RolesPerUser"
    ADD FOREIGN KEY ("roleId")
    REFERENCES prompt_sales."Roles" ("roleId") MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS prompt_sales."SystemLogs"
    ADD FOREIGN KEY ("moduleId")
    REFERENCES prompt_sales."Modules" ("moduleId") MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS prompt_sales."SystemLogs"
    ADD FOREIGN KEY ("systemLogTypeId")
    REFERENCES prompt_sales."SystemLogTypes" ("systemLogTypeId") MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS prompt_sales."SystemLogs"
    ADD FOREIGN KEY ("userId")
    REFERENCES prompt_sales."User" (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS prompt_sales."SystemLogs"
    ADD FOREIGN KEY ("logSourceId")
    REFERENCES prompt_sales."logSources" ("logSourceId") MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS prompt_sales."SystemLogs"
    ADD FOREIGN KEY ("logLevelId")
    REFERENCES prompt_sales."LogLevels" ("logLevelId") MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS prompt_sales."Subscription"
    ADD FOREIGN KEY ("billingId")
    REFERENCES prompt_sales."SubBilling" ("billingId") MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS prompt_sales."Features"
    ADD FOREIGN KEY ("featureTypeId")
    REFERENCES prompt_sales."featureType" ("featureTypeId") MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS prompt_sales."featuresPerSub"
    ADD FOREIGN KEY ("subId")
    REFERENCES prompt_sales."Subscription" ("subId") MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS prompt_sales."featuresPerSub"
    ADD FOREIGN KEY ("featureId")
    REFERENCES prompt_sales."Features" ("featureId") MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS prompt_sales."subsPerUser"
    ADD FOREIGN KEY ("subId")
    REFERENCES prompt_sales."Subscription" ("subId") MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS prompt_sales."subsPerUser"
    ADD FOREIGN KEY ("userId")
    REFERENCES prompt_sales."User" (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS prompt_sales."Payments"
    ADD FOREIGN KEY ("paymentTypeId")
    REFERENCES prompt_sales."PaymentTypes" ("paymentTypeId") MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS prompt_sales."Payments"
    ADD FOREIGN KEY ("paymentMethodId")
    REFERENCES prompt_sales."paymentMethod" ("paymentMetId") MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS prompt_sales."Payments"
    ADD FOREIGN KEY ("currencyId")
    REFERENCES prompt_sales."Currency" ("currencyId") MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS prompt_sales."Payments"
    ADD FOREIGN KEY ("subId")
    REFERENCES prompt_sales."Subscription" ("subId") MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS prompt_sales."Payments"
    ADD FOREIGN KEY ("companyId")
    REFERENCES prompt_sales."Companies" ("companyId") MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS prompt_sales."Currency"
    ADD FOREIGN KEY ("countryId")
    REFERENCES prompt_sales."Country" ("countryId") MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS prompt_sales."ExchangeRate"
    ADD FOREIGN KEY ("fromCurrency")
    REFERENCES prompt_sales."Currency" ("currencyId") MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS prompt_sales."ExchangeRate"
    ADD FOREIGN KEY ("toCurrency")
    REFERENCES prompt_sales."Currency" ("currencyId") MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS prompt_sales."Campaigns"
    ADD FOREIGN KEY ("intereractionsId")
    REFERENCES prompt_sales."Interactions" ("interactionId") MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS prompt_sales."Campaigns"
    ADD FOREIGN KEY ("calculatiosId")
    REFERENCES prompt_sales."Calculations" ("calculoId") MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS prompt_sales."ContactMethods"
    ADD FOREIGN KEY ("contactTypeId")
    REFERENCES prompt_sales."ContactMethodTypes" ("TypeId") MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS prompt_sales."contactCompany"
    ADD FOREIGN KEY ("companyId")
    REFERENCES prompt_sales."Companies" ("companyId") MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS prompt_sales."contactCompany"
    ADD FOREIGN KEY ("contactMehodId")
    REFERENCES prompt_sales."ContactMethods" ("contactMethodId") MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS prompt_sales."UserContact"
    ADD FOREIGN KEY ("UserId")
    REFERENCES prompt_sales."User" (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS prompt_sales."UserContact"
    ADD FOREIGN KEY ("contactMehodId")
    REFERENCES prompt_sales."ContactMethods" ("contactMethodId") MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS prompt_sales."CampaignChannels"
    ADD FOREIGN KEY ("campaignId")
    REFERENCES prompt_sales."Campaigns" ("campaignId") MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS prompt_sales."Leads"
    ADD FOREIGN KEY ("campaignId")
    REFERENCES prompt_sales."Campaigns" ("campaignId") MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS prompt_sales."Leads"
    ADD FOREIGN KEY ("countryId")
    REFERENCES prompt_sales."Country" ("countryId") MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS prompt_sales."salesSummary"
    ADD FOREIGN KEY ("campaignId")
    REFERENCES prompt_sales."Campaigns" ("campaignId") MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS prompt_sales."salesSummary"
    ADD FOREIGN KEY ("countryId")
    REFERENCES prompt_sales."Country" ("countryId") MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS prompt_sales."salesSummary"
    ADD FOREIGN KEY (currencyd)
    REFERENCES prompt_sales."Currency" ("currencyId") MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS prompt_sales."CampaignMarkets"
    ADD FOREIGN KEY ("AddressId")
    REFERENCES prompt_sales."Addresses" ("AddressId") MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS prompt_sales."CampaignMarkets"
    ADD FOREIGN KEY ("campaignId")
    REFERENCES prompt_sales."Campaigns" ("campaignId") MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS prompt_sales."Addresses"
    ADD FOREIGN KEY ("cityId")
    REFERENCES prompt_sales."Cities" ("cityId") MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS prompt_sales."Cities"
    ADD FOREIGN KEY ("stateId")
    REFERENCES prompt_sales."States" ("StateId") MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS prompt_sales."States"
    ADD FOREIGN KEY ("countryId")
    REFERENCES prompt_sales."Country" ("countryId") MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS prompt_sales."Providers"
    ADD FOREIGN KEY ("providerTypeId")
    REFERENCES prompt_sales."ProviderTypes" ("provderTypeId") MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS prompt_sales."ProviderAPIs"
    ADD FOREIGN KEY ("providerId")
    REFERENCES prompt_sales."Providers" ("providerId") MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS prompt_sales."ProviderAPIs"
    ADD FOREIGN KEY ("authId")
    REFERENCES prompt_sales."AuthMethods" ("authId") MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS prompt_sales."ProviderAPIs"
    ADD FOREIGN KEY ("typeId")
    REFERENCES prompt_sales."ApiTypes" ("typeId") MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS prompt_sales."MCPServers"
    ADD FOREIGN KEY ("providerId")
    REFERENCES prompt_sales."Providers" ("providerId") MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS prompt_sales."MCPServers"
    ADD FOREIGN KEY ("authId")
    REFERENCES prompt_sales."AuthMethods" ("authId") MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS prompt_sales."IntegrationCalls"
    ADD FOREIGN KEY ("companyId")
    REFERENCES prompt_sales."Companies" ("companyId") MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS prompt_sales."IntegrationCalls"
    ADD FOREIGN KEY ("providerId")
    REFERENCES prompt_sales."Providers" ("providerId") MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS prompt_sales."IntegrationCalls"
    ADD FOREIGN KEY ("apiId")
    REFERENCES prompt_sales."ProviderAPIs" ("apiId") MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS prompt_sales."callErrors"
    ADD FOREIGN KEY ("callId")
    REFERENCES prompt_sales."IntegrationCalls" ("callId") MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS prompt_sales."callErrors"
    ADD FOREIGN KEY ("errorTypeId")
    REFERENCES prompt_sales."CallErrorTypes" ("typeId") MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS prompt_sales."CallRetryLog"
    ADD FOREIGN KEY ("callId")
    REFERENCES prompt_sales."IntegrationCalls" ("callId") MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS prompt_sales."ETLJobs"
    ADD FOREIGN KEY ("endpointId")
    REFERENCES prompt_sales."ProviderAPIs" ("apiId") MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS prompt_sales."ETLDeltas"
    ADD FOREIGN KEY ("jobId")
    REFERENCES prompt_sales."ETLJobs" ("jobId") MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS prompt_sales."ETLDeltas"
    ADD FOREIGN KEY ("deltaTypeId")
    REFERENCES prompt_sales."DeltaTypes" ("TypeId") MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;

