-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://github.com/pgadmin-org/pgadmin4/issues/new/choose if you find any bugs, including reproduction steps.




CREATE TABLE IF NOT EXISTS public."User"
(
    id integer NOT NULL,
    "userNationalId" integer NOT NULL,
    "userFirstName" character varying(30) NOT NULL,
    "userLastName" character varying(30) NOT NULL,
    "userPassword" character varying(50) NOT NULL,
    enabled boolean NOT NULL DEFAULT true,
    "createdAt" timestamp without time zone NOT NULL,
    "updatedAt" timestamp without time zone,
    "lastLogin" timestamp without time zone,
    PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public."UserPermissions"
(
    "permissionId" integer NOT NULL,
    "userId" integer NOT NULL,
    "permisionStatus" boolean NOT NULL DEFAULT true,
    "createdAt" timestamp without time zone NOT NULL,
    "updatedAt" timestamp without time zone,
    enabled boolean NOT NULL DEFAULT true,
    "userEmail" character varying(60),
    PRIMARY KEY ("permissionId", "userId")
);

CREATE TABLE IF NOT EXISTS public."Permissions"
(
    "permissionId" integer NOT NULL,
    "permissionCode" character varying(16) NOT NULL,
    "permissionStatus" boolean NOT NULL DEFAULT true,
    "createdAt" timestamp without time zone NOT NULL,
    "updatedAt" timestamp without time zone,
    enabled boolean NOT NULL DEFAULT true,
    module integer NOT NULL,
    PRIMARY KEY ("permissionId")
);

CREATE TABLE IF NOT EXISTS public."Modules"
(
    "moduleId" integer NOT NULL,
    "moduleName" character varying(40) NOT NULL,
    PRIMARY KEY ("moduleId")
);

CREATE TABLE IF NOT EXISTS public."Applications"
(
    "AppId" integer NOT NULL,
    "appName" character varying(40) NOT NULL,
    "appType" character varying(20) NOT NULL,
    "moduleId" integer,
    PRIMARY KEY ("AppId")
);

CREATE TABLE IF NOT EXISTS public."Companies"
(
    "companyId" integer NOT NULL,
    legalld integer NOT NULL,
    "companyName" character varying(40) NOT NULL,
    "legalName" character varying(40) NOT NULL,
    status character varying(30)  NOT NULL,
    "createdAt" date NOT NULL,
    "updatedAt" date,
    enabled boolean DEFAULT true,
    PRIMARY KEY ("companyId")
);

CREATE TABLE IF NOT EXISTS public."UserInCompany"
(
    "userId" integer NOT NULL,
    "companyId" integer NOT NULL,
    status character varying(30) NOT NULL,
    "createdAt" date NOT NULL,
    "updatedAt" date,
    enabled boolean NOT NULL DEFAULT true,
    PRIMARY KEY ("userId", "companyId")
);

CREATE TABLE IF NOT EXISTS public."PermissionsPerRole"
(
    "roleId" integer NOT NULL,
    "permisionId" integer NOT NULL,
    "createdAt" date NOT NULL,
    "updatedAt" date,
    enabled boolean NOT NULL,
    status character varying(30) NOT NULL,
    PRIMARY KEY ("roleId", "permisionId")
);

CREATE TABLE IF NOT EXISTS public."Roles"
(
    "roleId" integer NOT NULL,
    "roleName" character varying(30) NOT NULL,
    "roleStatus" character varying(30) NOT NULL,
    "createdAt" timestamp without time zone NOT NULL,
    "updatedAt" timestamp without time zone,
    PRIMARY KEY ("roleId")
);

CREATE TABLE IF NOT EXISTS public."RolesPerUser"
(
    "userId" integer NOT NULL,
    "roleId" integer NOT NULL,
    status character varying(30) NOT NULL,
    "createdAt" timestamp without time zone NOT NULL,
    "upatedAt" timestamp without time zone NOT NULL,
    enabled boolean NOT NULL,
    PRIMARY KEY ("userId", "roleId")
);

CREATE TABLE IF NOT EXISTS public."SystemLogs"
(
    "systemLogId" integer NOT NULL,
    description character varying(250),
    "postTime" timestamp without time zone NOT NULL,
    checksum character varying(64),
    "systemLogTypeId" integer NOT NULL,
    "moduleId" integer NOT NULL,
    "userId" integer NOT NULL,
    "logSourceId" integer NOT NULL,
    "logLevelId" integer NOT NULL,
    PRIMARY KEY ("systemLogId")
);

CREATE TABLE IF NOT EXISTS public."LogLevels"
(
    "logLevelId" integer NOT NULL,
    name character varying(30) NOT NULL,
    PRIMARY KEY ("logLevelId")
);

CREATE TABLE IF NOT EXISTS public."logSources"
(
    "logSourceId" integer NOT NULL,
    name character varying(30) NOT NULL,
    PRIMARY KEY ("logSourceId")
);

CREATE TABLE IF NOT EXISTS public."SystemLogTypes"
(
    "systemLogTypeId" integer NOT NULL,
    name character varying(30) NOT NULL,
    PRIMARY KEY ("systemLogTypeId")
);

CREATE TABLE IF NOT EXISTS public."Subscription"
(
    "subId" integer NOT NULL,
    "subName" character varying(45) NOT NULL,
    "billingId" integer NOT NULL,
    status character varying(30) NOT NULL,
    description character varying(200),
    "createdAt" timestamp without time zone NOT NULL,
    "updatedAt" timestamp without time zone,
    enabled boolean NOT NULL DEFAULT true,
    PRIMARY KEY ("subId"),
    UNIQUE ("billingId")
);

CREATE TABLE IF NOT EXISTS public."Features"
(
    "featureId" integer NOT NULL,
    "featureTypeId" integer NOT NULL,
    name character varying(30) NOT NULL,
    description text NOT NULL,
    enabled boolean NOT NULL DEFAULT false,
    "createdAt" timestamp without time zone NOT NULL,
    "updatedAt" timestamp without time zone NOT NULL,
    PRIMARY KEY ("featureId")
);

CREATE TABLE IF NOT EXISTS public."featuresPerSub"
(
    "subId" integer NOT NULL,
    "featureId" integer NOT NULL,
    uses integer NOT NULL,
    enabled boolean NOT NULL DEFAULT true,
    "createdAt" timestamp without time zone NOT NULL,
    "updatedAt" timestamp without time zone,
    PRIMARY KEY ("subId", "featureId")
);

CREATE TABLE IF NOT EXISTS public."subsPerUser"
(
    "subId" integer NOT NULL,
    "userId" integer NOT NULL,
    enabled boolean NOT NULL DEFAULT true,
    "createdAt" timestamp without time zone NOT NULL,
    "updatedAt" timestamp without time zone,
    PRIMARY KEY ("subId", "userId")
);

CREATE TABLE IF NOT EXISTS public."featureType"
(
    "featureTypeId" integer NOT NULL,
    name character varying(30) NOT NULL,
    description character varying(200),
    PRIMARY KEY ("featureTypeId")
);

CREATE TABLE IF NOT EXISTS public."Payments"
(
    "paymentId" integer NOT NULL,
    amount numeric(12, 2) NOT NULL,
    "createdAt" timestamp without time zone NOT NULL,
    "updatedAt" timestamp without time zone,
    status character varying(30) NOT NULL,
    cheksum character varying(64),
    "paymentTypeId" integer NOT NULL,
    "companyId" integer NOT NULL,
    "subId" integer NOT NULL,
    "currencyId" integer NOT NULL,
    "paymentMethodId" integer NOT NULL,
    PRIMARY KEY ("paymentId")
);

CREATE TABLE IF NOT EXISTS public."PaymentTypes"
(
    "paymentTypeId" integer NOT NULL,
    name character varying(30),
    PRIMARY KEY ("paymentTypeId")
);

CREATE TABLE IF NOT EXISTS public."paymentMethod"
(
    "paymentMetId" integer NOT NULL,
    name character varying(30),
    PRIMARY KEY ("paymentMetId")
);

CREATE TABLE IF NOT EXISTS public."Currency"
(
    "currencyId" integer NOT NULL,
    name character varying(30) NOT NULL,
    code bit varying(4) NOT NULL,
    symbol character varying(2) NOT NULL,
    "countryId" integer NOT NULL,
    PRIMARY KEY ("currencyId")
);

CREATE TABLE IF NOT EXISTS public."ExchangeRate"
(
    "exchangeRateId" integer NOT NULL,
    "startDate" timestamp without time zone NOT NULL,
    "endDate" timestamp without time zone,
    "fromCurrency" integer NOT NULL,
    "toCurrency" integer NOT NULL,
    enabled boolean NOT NULL DEFAULT true,
    PRIMARY KEY ("exchangeRateId"),
    UNIQUE ("fromCurrency"),
    UNIQUE ("toCurrency")
);

CREATE TABLE IF NOT EXISTS public."Country"
(
    "countryId" integer NOT NULL,
    name character varying(30),
    PRIMARY KEY ("countryId")
);

COMMENT ON TABLE public."Country"
    IS 'Se ocupa todo el patron de direcciones?
o solo como se ocupa el país está bien';

CREATE TABLE IF NOT EXISTS public."Campaigns"
(
    "campaignId" integer NOT NULL,
    "companyId" integer NOT NULL,
    name character varying,
    status character varying(30) NOT NULL,
    "startDate" timestamp without time zone NOT NULL,
    "endDate" timestamp without time zone,
    enabled boolean NOT NULL DEFAULT true,
    "budgetAmount" numeric(10, 2) NOT NULL,
    "createdAt" timestamp without time zone NOT NULL,
    "updatedAt" timestamp without time zone,
    description character varying(200),
    "intereractionsId" integer NOT NULL,
    "calculatiosId" integer NOT NULL,
    PRIMARY KEY ("campaignId")
);

CREATE TABLE IF NOT EXISTS public."ContactMethods"
(
    "contactMethodId" integer NOT NULL,
    value character varying(100) NOT NULL,
    status character varying(30) NOT NULL,
    "createdAt" timestamp without time zone NOT NULL,
    "updatedAt" timestamp without time zone,
    enabled boolean NOT NULL DEFAULT true,
    "contactTypeId" integer NOT NULL,
    PRIMARY KEY ("contactMethodId"),
    UNIQUE ("contactTypeId")
);

CREATE TABLE IF NOT EXISTS public."ContactMethodTypes"
(
    "TypeId" integer NOT NULL,
    name character varying(30) NOT NULL,
    PRIMARY KEY ("TypeId")
);

CREATE TABLE IF NOT EXISTS public."contactCompany"
(
    "companyId" integer NOT NULL,
    "contactMehodId" integer NOT NULL,
    status character varying(40) NOT NULL,
    "createdAt" timestamp without time zone NOT NULL,
    "updatedAt" timestamp without time zone,
    enabled boolean NOT NULL DEFAULT true,
    PRIMARY KEY ("companyId", "contactMehodId")
);

CREATE TABLE IF NOT EXISTS public."UserContact"
(
    "UserId" integer NOT NULL,
    "contactMehodId" integer NOT NULL,
    status character varying(40) NOT NULL,
    "createdAt" timestamp without time zone NOT NULL,
    "updatedAt" timestamp without time zone,
    enabled boolean NOT NULL DEFAULT true,
    PRIMARY KEY ("contactMehodId", "UserId")
);

CREATE TABLE IF NOT EXISTS public."Interactions"
(
    "interactionId" integer NOT NULL,
    clicks integer,
    likes integer,
    comments integer,
    reactions integer,
    shares integer,
    "usersReached" integer,
    PRIMARY KEY ("interactionId")
);

CREATE TABLE IF NOT EXISTS public."Calculations"
(
    "calculoId" integer NOT NULL,
    "clickRate" numeric(6, 3),
    "conversionRate" numeric(6, 3),
    "ROI" numeric(9, 3),
    "engagementRate" numeric(6, 3),
    "createdAt" timestamp without time zone,
    "totalSpent" numeric(10, 2),
    "totalRevenue" numeric(10, 2),
    PRIMARY KEY ("calculoId")
);

CREATE TABLE IF NOT EXISTS public."CampaignChannels"
(
    "channelId" integer NOT NULL,
    "campaignId" integer NOT NULL,
    name character varying(30) NOT NULL,
    "totalSpent" numeric(10, 2),
    "createdAt" timestamp without time zone NOT NULL,
    "updatedAt" timestamp without time zone,
    enabled boolean NOT NULL DEFAULT true,
    PRIMARY KEY ("channelId")
);

CREATE TABLE IF NOT EXISTS public."Leads"
(
    "leadId" integer NOT NULL,
    "campaignId" integer NOT NULL,
    "sourceSystem" integer,
    name character varying(60) NOT NULL,
    email character varying(60) NOT NULL,
    "number" character varying(20) NOT NULL,
    "countryId" integer NOT NULL,
    status character varying(30) NOT NULL,
    score numeric(3, 1),
    "createdAt" timestamp without time zone NOT NULL,
    "updatedAt" timestamp without time zone,
    enabled boolean NOT NULL DEFAULT true,
    PRIMARY KEY ("leadId"),
    UNIQUE ("countryId")
);

CREATE TABLE IF NOT EXISTS public."salesSummary"
(
    "salesSumId" integer NOT NULL,
    "campaignId" integer NOT NULL,
    "countryId" integer NOT NULL,
    date date NOT NULL,
    orders integer NOT NULL,
    "salesAmount" numeric(10, 2) NOT NULL,
    "returnsAmount" numeric(10, 2) NOT NULL,
    "adsRevenue" numeric(10, 2) NOT NULL,
    "sourceSystemId" character varying(30),
    currencyd integer,
    PRIMARY KEY ("salesSumId")
);

CREATE TABLE IF NOT EXISTS public."CampaignMarkets"
(
    "marketId" integer NOT NULL,
    "AddressId" integer NOT NULL,
    "budgetAllocation" numeric(5, 2) NOT NULL,
    enabled boolean NOT NULL DEFAULT true,
    "createdAt" timestamp without time zone NOT NULL,
    "updatedAt" timestamp without time zone,
    "campaignId" integer NOT NULL,
    PRIMARY KEY ("marketId")
);

CREATE TABLE IF NOT EXISTS public."Addresses"
(
    "AddressId" integer NOT NULL,
    address1 character varying(60) NOT NULL,
    address2 character varying(60) NOT NULL,
    zipcode character varying(12) NOT NULL,
    geolocation point NOT NULL,
    status character varying(30) NOT NULL,
    "createdAt" timestamp without time zone NOT NULL,
    "updatedAt" timestamp without time zone,
    enabled boolean NOT NULL DEFAULT true,
    "cityId" integer NOT NULL,
    PRIMARY KEY ("AddressId")
);

CREATE TABLE IF NOT EXISTS public."Cities"
(
    "cityId" integer NOT NULL,
    name character varying(40) NOT NULL,
    "stateId" integer NOT NULL,
    PRIMARY KEY ("cityId")
);

CREATE TABLE IF NOT EXISTS public."States"
(
    "StateId" integer NOT NULL,
    name character varying(40) NOT NULL,
    "countryId" integer NOT NULL,
    PRIMARY KEY ("StateId")
);

CREATE TABLE IF NOT EXISTS public."Providers"
(
    "providerId" integer NOT NULL,
    "providerTypeId" integer NOT NULL,
    name character varying(40) NOT NULL,
    "baseUrl" character varying(200) NOT NULL,
    status character varying(40),
    description character varying(250),
    "createdAt" timestamp without time zone NOT NULL,
    "updatedAt" timestamp without time zone,
    enabled boolean NOT NULL DEFAULT true,
    PRIMARY KEY ("providerId")
);

CREATE TABLE IF NOT EXISTS public."ProviderTypes"
(
    "provderTypeId" integer NOT NULL,
    name character varying(40) NOT NULL,
    description character varying(250),
    "createdAt" timestamp without time zone NOT NULL,
    "updatedAt" timestamp without time zone,
    enabled boolean NOT NULL DEFAULT true,
    PRIMARY KEY ("provderTypeId")
);

CREATE TABLE IF NOT EXISTS public."ProviderAPIs"
(
    "apiId" integer NOT NULL,
    "providerId" integer NOT NULL,
    name character varying(40) NOT NULL,
    "baseUrl" character varying(200) NOT NULL,
    "authId" integer NOT NULL,
    enabled boolean NOT NULL DEFAULT true,
    "createdAt" timestamp without time zone NOT NULL,
    "updatedAt" timestamp without time zone,
    request jsonb NOT NULL,
    response jsonb,
    endpoint character varying(100) NOT NULL,
    "typeId" integer,
    PRIMARY KEY ("apiId")
);

CREATE TABLE IF NOT EXISTS public."MCPServers"
(
    "mcpId" integer NOT NULL,
    "providerId" integer NOT NULL,
    name character varying(40) NOT NULL,
    url character varying(200) NOT NULL,
    "maxConcurrentCalls" integer NOT NULL,
    "authId" integer NOT NULL,
    enabled boolean NOT NULL DEFAULT true,
    "lastCall" timestamp without time zone,
    "createdAt" timestamp without time zone,
    "updatedAt" integer NOT NULL,
    PRIMARY KEY ("mcpId")
);

CREATE TABLE IF NOT EXISTS public."AuthMethods"
(
    "authId" integer NOT NULL,
    name character varying(30) NOT NULL,
    description character varying(200),
    enabled boolean NOT NULL DEFAULT true,
    "createdAt" timestamp without time zone NOT NULL,
    "updatedAt" timestamp without time zone,
    PRIMARY KEY ("authId")
);

CREATE TABLE IF NOT EXISTS public."IntegrationCalls"
(
    "callId" integer NOT NULL,
    "companyId" integer NOT NULL,
    "providerId" integer NOT NULL,
    "apiId" integer,
    "mcpToolId" integer,
    operation character varying NOT NULL,
    "responseTime" interval NOT NULL,
    "excecutedAt" timestamp without time zone NOT NULL,
    status character varying NOT NULL,
    "updatedAt" timestamp without time zone,
    PRIMARY KEY ("callId")
);

CREATE TABLE IF NOT EXISTS public."callErrors"
(
    "errorId" integer NOT NULL,
    "callId" integer NOT NULL,
    "errorCode" character varying(20) NOT NULL,
    "errorMessage" character varying(150) NOT NULL,
    "errorTypeId" integer,
    retryable boolean NOT NULL DEFAULT true,
    "createdAt" timestamp without time zone NOT NULL,
    PRIMARY KEY ("errorId")
);

CREATE TABLE IF NOT EXISTS public."CallErrorTypes"
(
    "typeId" integer NOT NULL,
    name character varying(50) NOT NULL,
    PRIMARY KEY ("typeId")
);

CREATE TABLE IF NOT EXISTS public."CallRetryLog"
(
    "retryId" integer NOT NULL,
    "callId" integer NOT NULL,
    attempts integer NOT NULL,
    "maxAttempts" integer NOT NULL,
    "createdAt" timestamp without time zone NOT NULL,
    "updadtedAt" timestamp without time zone,
    status character varying,
    PRIMARY KEY ("retryId")
);

CREATE TABLE IF NOT EXISTS public."ETLJobs"
(
    "jobId" integer NOT NULL,
    name character varying(30) NOT NULL,
    description character varying(200) NOT NULL,
    "sourceSystem" character varying(30) NOT NULL,
    enabled boolean NOT NULL DEFAULT true,
    "createdAt" timestamp without time zone NOT NULL,
    "updatedAt" timestamp without time zone,
    "endpointId" integer,
    "targetTable" character varying,
    PRIMARY KEY ("jobId")
);

CREATE TABLE IF NOT EXISTS public."ApiTypes"
(
    "typeId" integer NOT NULL,
    name character varying(50) NOT NULL,
    PRIMARY KEY ("typeId")
);

CREATE TABLE IF NOT EXISTS public."ETLDeltas"
(
    "deltaId" integer NOT NULL,
    "jobId" integer NOT NULL,
    "sourceSystem" character varying(30) NOT NULL,
    "deltaTypeId" integer NOT NULL,
    description character varying(200) NOT NULL,
    "createdAt" timestamp without time zone NOT NULL,
    "updatedAt" timestamp without time zone,
    status character varying(30) NOT NULL,
    "entityName" character varying(30),
    PRIMARY KEY ("deltaId"),
    UNIQUE ("deltaTypeId")
);

CREATE TABLE IF NOT EXISTS public."DeltaTypes"
(
    "TypeId" integer NOT NULL,
    name character varying(30) NOT NULL,
    PRIMARY KEY ("TypeId")
);

CREATE TABLE IF NOT EXISTS public."SubBilling"
(
    "billingId" integer NOT NULL,
    "paymentFrequency" character varying(30) NOT NULL,
    "startDate" timestamp without time zone NOT NULL,
    "endDate" timestamp without time zone NOT NULL,
    status character varying(30) NOT NULL,
    price numeric(6, 2) NOT NULL,
    PRIMARY KEY ("billingId")
);

CREATE TABLE IF NOT EXISTS public."RawPromptAds" (
  -- Datos de la vista 
  campaign_id           BIGINT,
  campaign_name         VARCHAR(200),
  start_date            TIMESTAMPTZ,
  end_date              TIMESTAMPTZ,
  campaign_budget       NUMERIC(12,2),

  company_id            BIGINT,
  company_name          VARCHAR(200),

  ad_id                 BIGINT,
  ad_name               VARCHAR(200),
  ad_created_at         TIMESTAMPTZ,
  ad_enabled            BOOLEAN,
  ad_status             VARCHAR(50),
  ad_type               VARCHAR(50),

  channels              TEXT,         
  target_markets        TEXT,         

  total_impressions     BIGINT,
  total_clicks          BIGINT,
  total_interactions    BIGINT,
  total_reach           BIGINT,
  total_hours_viewed    NUMERIC(18,3),
  total_cost            NUMERIC(14,2),
  total_revenue         NUMERIC(14,2),

  snapshot_date         DATE NOT NULL DEFAULT CURRENT_DATE, 
  source_system         VARCHAR(30) NOT NULL DEFAULT 'PromptAds',
  source_view           VARCHAR(128) NOT NULL DEFAULT 'dbo.vwPromptAdsSimpleSummary',
  etl_run_id            BIGINT,
  raw_checksum          CHAR(64),      
  load_ts               TIMESTAMPTZ NOT NULL DEFAULT NOW(),

  raw_id                BIGSERIAL PRIMARY KEY
);




CREATE TABLE IF NOT EXISTS public."RawPromptCrm" (
  lead_id                   BIGINT,
  lead_token                VARCHAR(100),
  created_at                TIMESTAMPTZ,
  utm_source                VARCHAR(100),
  utm_medium                VARCHAR(100),
  utm_campaign              VARCHAR(150),
  first_name                VARCHAR(120),
  last_name                 VARCHAR(120),
  email                     VARCHAR(200),
  phone_number              VARCHAR(40),
  lead_score                NUMERIC(6,2),
  lead_status               VARCHAR(60),

  subscriber_id             BIGINT,
  subscriber_name           VARCHAR(200),

  marketing_channel_id      BIGINT,
  channel_name              VARCHAR(120),
  channel_type_name         VARCHAR(120),

  assigned_to_user_id       BIGINT,
  assigned_user_name        VARCHAR(200),
  assigned_at               TIMESTAMPTZ,
  last_contacted_at         TIMESTAMPTZ,
  next_followup_date        DATE,
  converted_to_customer_at  TIMESTAMPTZ,
  conversion_value          NUMERIC(14,2),

  total_events              BIGINT,
  conversion_events         BIGINT,
  total_conversion_amount   NUMERIC(14,2),
  last_event_at             TIMESTAMPTZ,

  snapshot_date             DATE NOT NULL DEFAULT CURRENT_DATE,
  source_system             VARCHAR(30) NOT NULL DEFAULT 'PromptCrm',
  source_view               VARCHAR(128) NOT NULL DEFAULT 'crm.vwPromptCrmSimpleSummary',
  etl_run_id                BIGINT,
  raw_checksum              CHAR(64),
  load_ts                   TIMESTAMPTZ NOT NULL DEFAULT NOW(),

  raw_id                    BIGSERIAL PRIMARY KEY
);

alter table if exists public."RawPromptCrm" drop column converted_to_customer_at;
alter table if exists public."RawPromptCrm" drop column conversion_value;

ALTER TABLE IF EXISTS public."Permissions"
    ADD FOREIGN KEY (module)
    REFERENCES public."Modules" ("moduleId") MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public."UserPermissions"
    ADD FOREIGN KEY ("userId")
    REFERENCES public."User" (id)
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;

ALTER TABLE IF EXISTS public."UserPermissions"
    ADD FOREIGN KEY ("permissionId")
    REFERENCES public."Permissions" ("permissionId")
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public."Applications"
    ADD FOREIGN KEY ("moduleId")
    REFERENCES public."Modules" ("moduleId") MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public."UserInCompany"
    ADD FOREIGN KEY ("companyId")
    REFERENCES public."Companies" ("companyId") MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public."UserInCompany"
    ADD FOREIGN KEY ("userId")
    REFERENCES public."User" (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public."PermissionsPerRole"
    ADD FOREIGN KEY ("permisionId")
    REFERENCES public."Permissions" ("permissionId") MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public."PermissionsPerRole"
    ADD FOREIGN KEY ("roleId")
    REFERENCES public."Roles" ("roleId") MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public."RolesPerUser"
    ADD FOREIGN KEY ("userId")
    REFERENCES public."User" (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public."RolesPerUser"
    ADD FOREIGN KEY ("roleId")
    REFERENCES public."Roles" ("roleId") MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public."SystemLogs"
    ADD FOREIGN KEY ("moduleId")
    REFERENCES public."Modules" ("moduleId") MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public."SystemLogs"
    ADD FOREIGN KEY ("systemLogTypeId")
    REFERENCES public."SystemLogTypes" ("systemLogTypeId") MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public."SystemLogs"
    ADD FOREIGN KEY ("userId")
    REFERENCES public."User" (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public."SystemLogs"
    ADD FOREIGN KEY ("logSourceId")
    REFERENCES public."logSources" ("logSourceId") MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public."SystemLogs"
    ADD FOREIGN KEY ("logLevelId")
    REFERENCES public."LogLevels" ("logLevelId") MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public."Subscription"
    ADD FOREIGN KEY ("billingId")
    REFERENCES public."SubBilling" ("billingId") MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public."Features"
    ADD FOREIGN KEY ("featureTypeId")
    REFERENCES public."featureType" ("featureTypeId") MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public."featuresPerSub"
    ADD FOREIGN KEY ("subId")
    REFERENCES public."Subscription" ("subId") MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public."featuresPerSub"
    ADD FOREIGN KEY ("featureId")
    REFERENCES public."Features" ("featureId") MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public."subsPerUser"
    ADD FOREIGN KEY ("subId")
    REFERENCES public."Subscription" ("subId") MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public."subsPerUser"
    ADD FOREIGN KEY ("userId")
    REFERENCES public."User" (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public."Payments"
    ADD FOREIGN KEY ("paymentTypeId")
    REFERENCES public."PaymentTypes" ("paymentTypeId") MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public."Payments"
    ADD FOREIGN KEY ("paymentMethodId")
    REFERENCES public."paymentMethod" ("paymentMetId") MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public."Payments"
    ADD FOREIGN KEY ("currencyId")
    REFERENCES public."Currency" ("currencyId") MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public."Payments"
    ADD FOREIGN KEY ("subId")
    REFERENCES public."Subscription" ("subId") MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public."Payments"
    ADD FOREIGN KEY ("companyId")
    REFERENCES public."Companies" ("companyId") MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public."Currency"
    ADD FOREIGN KEY ("countryId")
    REFERENCES public."Country" ("countryId") MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public."ExchangeRate"
    ADD FOREIGN KEY ("fromCurrency")
    REFERENCES public."Currency" ("currencyId") MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public."ExchangeRate"
    ADD FOREIGN KEY ("toCurrency")
    REFERENCES public."Currency" ("currencyId") MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public."Campaigns"
    ADD FOREIGN KEY ("intereractionsId")
    REFERENCES public."Interactions" ("interactionId") MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public."Campaigns"
    ADD FOREIGN KEY ("calculatiosId")
    REFERENCES public."Calculations" ("calculoId") MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public."ContactMethods"
    ADD FOREIGN KEY ("contactTypeId")
    REFERENCES public."ContactMethodTypes" ("TypeId") MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public."contactCompany"
    ADD FOREIGN KEY ("companyId")
    REFERENCES public."Companies" ("companyId") MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public."contactCompany"
    ADD FOREIGN KEY ("contactMehodId")
    REFERENCES public."ContactMethods" ("contactMethodId") MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public."UserContact"
    ADD FOREIGN KEY ("UserId")
    REFERENCES public."User" (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public."UserContact"
    ADD FOREIGN KEY ("contactMehodId")
    REFERENCES public."ContactMethods" ("contactMethodId") MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public."CampaignChannels"
    ADD FOREIGN KEY ("campaignId")
    REFERENCES public."Campaigns" ("campaignId") MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public."Leads"
    ADD FOREIGN KEY ("campaignId")
    REFERENCES public."Campaigns" ("campaignId") MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public."Leads"
    ADD FOREIGN KEY ("countryId")
    REFERENCES public."Country" ("countryId") MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public."salesSummary"
    ADD FOREIGN KEY ("campaignId")
    REFERENCES public."Campaigns" ("campaignId") MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public."salesSummary"
    ADD FOREIGN KEY ("countryId")
    REFERENCES public."Country" ("countryId") MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public."salesSummary"
    ADD FOREIGN KEY (currencyd)
    REFERENCES public."Currency" ("currencyId") MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public."CampaignMarkets"
    ADD FOREIGN KEY ("AddressId")
    REFERENCES public."Addresses" ("AddressId") MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public."CampaignMarkets"
    ADD FOREIGN KEY ("campaignId")
    REFERENCES public."Campaigns" ("campaignId") MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public."Addresses"
    ADD FOREIGN KEY ("cityId")
    REFERENCES public."Cities" ("cityId") MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public."Cities"
    ADD FOREIGN KEY ("stateId")
    REFERENCES public."States" ("StateId") MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public."States"
    ADD FOREIGN KEY ("countryId")
    REFERENCES public."Country" ("countryId") MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public."Providers"
    ADD FOREIGN KEY ("providerTypeId")
    REFERENCES public."ProviderTypes" ("provderTypeId") MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public."ProviderAPIs"
    ADD FOREIGN KEY ("providerId")
    REFERENCES public."Providers" ("providerId") MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public."ProviderAPIs"
    ADD FOREIGN KEY ("authId")
    REFERENCES public."AuthMethods" ("authId") MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public."ProviderAPIs"
    ADD FOREIGN KEY ("typeId")
    REFERENCES public."ApiTypes" ("typeId") MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public."MCPServers"
    ADD FOREIGN KEY ("providerId")
    REFERENCES public."Providers" ("providerId") MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public."MCPServers"
    ADD FOREIGN KEY ("authId")
    REFERENCES public."AuthMethods" ("authId") MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public."IntegrationCalls"
    ADD FOREIGN KEY ("companyId")
    REFERENCES public."Companies" ("companyId") MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public."IntegrationCalls"
    ADD FOREIGN KEY ("providerId")
    REFERENCES public."Providers" ("providerId") MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public."IntegrationCalls"
    ADD FOREIGN KEY ("apiId")
    REFERENCES public."ProviderAPIs" ("apiId") MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public."callErrors"
    ADD FOREIGN KEY ("callId")
    REFERENCES public."IntegrationCalls" ("callId") MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public."callErrors"
    ADD FOREIGN KEY ("errorTypeId")
    REFERENCES public."CallErrorTypes" ("typeId") MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public."CallRetryLog"
    ADD FOREIGN KEY ("callId")
    REFERENCES public."IntegrationCalls" ("callId") MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public."ETLJobs"
    ADD FOREIGN KEY ("endpointId")
    REFERENCES public."ProviderAPIs" ("apiId") MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public."ETLDeltas"
    ADD FOREIGN KEY ("jobId")
    REFERENCES public."ETLJobs" ("jobId") MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public."ETLDeltas"
    ADD FOREIGN KEY ("deltaTypeId")
    REFERENCES public."DeltaTypes" ("TypeId") MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


