apiVersion: v1
kind: Namespace
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","kind":"Namespace","metadata":{"annotations":{},"labels":{"env":"dev","project":"promptSales"},"name":"promptcontent-dev"}}
  creationTimestamp: "2025-11-09T21:33:05Z"
  labels:
    env: dev
    kubernetes.io/metadata.name: promptcontent-dev
    project: promptSales
  name: promptcontent-dev
  resourceVersion: "532"
  uid: 95040d9f-3462-4c75-aab1-9eb23e8d651c
spec:
  finalizers:
  - kubernetes
status:
  phase: Active
